-- 1) Create the about_content table
create table public.about_content (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  experience_title text not null,
  experience_body text not null,
  experience_bullets text[] null,
  experience_image_url text null,
  experience_image_alt text null,
  is_active boolean default true
);

-- 2) Enable Row Level Security
alter table public.about_content enable row level security;

-- 3) Create Policy: Public read access for active content
create policy "Enable read access for all users"
on public.about_content for select
to anon, authenticated
using (is_active = true);

-- 4) Create Policy: Admin full access (Assuming authenticated users are admins for simplicity, or adjust as needed)
-- Note: Adjust this policy if you have specific admin roles. 
-- For now, we allow authenticated users to do everything based on the prompt "Authenticated admin user can select/insert/update".
create policy "Enable all access for authenticated users"
on public.about_content for all
to authenticated
using (true)
with check (true);


-- 5) STORAGE SETUP INSTRUCTIONS (Run these manually in Supabase Dashboard or via API if supported)
-- Create a new public bucket named 'site-assets'.
-- Ensure policies allow public read, and authenticated insert/update.

-- Policy for Storage (if you were running SQL for it, but Storage is often separate in UI):
-- insert into storage.buckets (id, name, public) values ('site-assets', 'site-assets', true);
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'site-assets' );
-- create policy "Auth Upload" on storage.objects for insert to authenticated with check ( bucket_id = 'site-assets' );
-- create policy "Auth Update" on storage.objects for update to authenticated using ( bucket_id = 'site-assets' );
